# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'BleClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BleClient
  pod 'MultiplatformBleAdapter', :git => 'git@github.com:dpwiese/MultiPlatformBleAdapter.git', :commit => 'e1cc5411167147804225a8141c294a8795ddfc36'
end
