# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'BleClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BleClient
  pod 'MultiplatformBleAdapter', :git => 'git@github.com:dpwiese/MultiPlatformBleAdapter.git', :commit => '66b7323c2fdd56f72a833bd42b038ade4a435405'
end
